# Generated by Django 4.0.4 on 2022-05-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
    ]
